use std::fmt::Write as FmtWrite;
use std::fs::{File, OpenOptions};
use std::io::{BufReader, BufWriter};
use std::path::PathBuf;

use anyhow::{anyhow, Context, Result};
use clap::{Parser, Subcommand};
use rand_core::{OsRng, RngCore};
use reqwest::Url;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use zectime_anchor::{
    fetch_timestamp, publish_timestamp, Network, TxId, ZalletAuth, ZalletConfig, ZalletRpc,
};
use zectime_prover::timestamp::{
    compute_commitment_bytes, prove_timestamp, timestamp_verifying_key_for, TimestampProof,
    TimestampProvingArtifacts, TimestampWitness, TIMESTAMP_CIRCUIT_K,
};
use zectime_prover::timestamp_predicate::{
    prove_timestamp_predicate, timestamp_predicate_verifying_key_for, PredicateWitness,
    TimestampPredicateProof, TimestampPredicateProvingArtifacts, TIMESTAMP_PREDICATE_CIRCUIT_K,
    TIMESTAMP_PREDICATE_PUBLIC_INPUTS,
};
use zectime_prover::{read_params, write_params};
use zectime_verifier::{verify_timestamp, verify_timestamp_predicate};

const MAX_PROOF_BYTES: u64 = 8 * 1024 * 1024;

#[derive(Parser)]
#[command(name = "zectime")]
#[command(about = "Private Zcash timestamp receipts with blind ZK commitments")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Generate IPA parameters for timestamp-open proofs.
    Setup(SetupArgs),
    /// Timestamp receipt operations.
    Timestamp(TimestampArgs),
}

#[derive(clap::Args)]
struct SetupArgs {
    /// Output file for serialized IPA parameters.
    #[arg(long)]
    params: PathBuf,
    /// Circuit size parameter.
    #[arg(long, default_value_t = TIMESTAMP_CIRCUIT_K)]
    k: u32,
}

#[derive(clap::Args)]
struct TimestampArgs {
    #[command(subcommand)]
    command: TimestampCommand,
}

#[derive(Subcommand)]
enum TimestampCommand {
    /// Hash a file, create a blind commitment, and write receipt JSON.
    Stamp(TimestampStampArgs),
    /// Build a Halo2 proof that opens a receipt commitment.
    Reveal(TimestampRevealArgs),
    /// Verify a timestamp-open proof.
    Verify(TimestampVerifyArgs),
    /// Publish a receipt commitment in a Zcash Orchard memo via zallet.
    Anchor(TimestampAnchorArgs),
    /// Fetch a confirmed timestamp memo by txid.
    Fetch(TimestampFetchArgs),
    /// Generate IPA parameters for predicate proofs.
    PredicateSetup(TimestampPredicateSetupArgs),
    /// Build a predicate proof from witness JSON.
    PredicateProve(TimestampPredicateProveArgs),
    /// Verify a predicate proof.
    PredicateVerify(TimestampPredicateVerifyArgs),
}

#[derive(clap::Args)]
struct TimestampStampArgs {
    /// Document to stamp.
    #[arg(long)]
    file: PathBuf,
    /// Optional confirmed block height. Draft receipts use 0.
    #[arg(long)]
    block_height: Option<u64>,
    /// Output receipt JSON.
    #[arg(long, default_value = "zectime-zk-receipt.json")]
    out: PathBuf,
}

#[derive(clap::Args)]
struct TimestampRevealArgs {
    /// IPA params from `zectime setup`.
    #[arg(long)]
    params: PathBuf,
    /// Receipt JSON generated by `timestamp stamp`.
    #[arg(long)]
    receipt: PathBuf,
    /// Output proof file.
    #[arg(long, default_value = "timestamp-proof.json")]
    out: PathBuf,
}

#[derive(clap::Args)]
struct TimestampVerifyArgs {
    /// IPA params from `zectime setup`.
    #[arg(long)]
    params: PathBuf,
    /// Proof file produced by `timestamp reveal`.
    #[arg(long)]
    proof: PathBuf,
    /// Optional receipt JSON to cross-check commitment and block height.
    #[arg(long)]
    receipt: Option<PathBuf>,
}

#[derive(clap::Args)]
struct TimestampAnchorArgs {
    /// Receipt JSON generated by `timestamp stamp`.
    #[arg(long)]
    receipt: PathBuf,
    /// zallet JSON-RPC URL.
    #[arg(long, env = "ZECTIME_RPC_URL")]
    rpc_url: Url,
    /// Unified address used for the shielded self-spend.
    #[arg(long, env = "ZECTIME_FROM_ADDRESS")]
    from_address: String,
    /// Network: regtest, testnet, or mainnet.
    #[arg(long, default_value = "regtest", value_parser = parse_network)]
    network: Network,
    /// Optional RPC basic-auth user.
    #[arg(long, env = "ZECTIME_RPC_USER")]
    rpc_user: Option<String>,
    /// Optional RPC basic-auth password.
    #[arg(long, env = "ZECTIME_RPC_PASSWORD")]
    rpc_password: Option<String>,
    /// Output anchor metadata JSON.
    #[arg(long, default_value = "timestamp-anchor.json")]
    out: PathBuf,
}

#[derive(clap::Args)]
struct TimestampFetchArgs {
    /// Transaction id carrying the timestamp memo.
    #[arg(long)]
    txid: String,
    /// zallet JSON-RPC URL.
    #[arg(long, env = "ZECTIME_RPC_URL")]
    rpc_url: Url,
    /// Network: regtest, testnet, or mainnet.
    #[arg(long, default_value = "regtest", value_parser = parse_network)]
    network: Network,
    /// Optional RPC basic-auth user.
    #[arg(long, env = "ZECTIME_RPC_USER")]
    rpc_user: Option<String>,
    /// Optional RPC basic-auth password.
    #[arg(long, env = "ZECTIME_RPC_PASSWORD")]
    rpc_password: Option<String>,
    /// Optional receipt JSON to cross-check.
    #[arg(long)]
    receipt: Option<PathBuf>,
    /// Optional output metadata JSON.
    #[arg(long)]
    out: Option<PathBuf>,
}

#[derive(clap::Args)]
struct TimestampPredicateSetupArgs {
    /// Output predicate params file.
    #[arg(long)]
    params: PathBuf,
    /// Circuit size parameter.
    #[arg(long, default_value_t = TIMESTAMP_PREDICATE_CIRCUIT_K)]
    k: u32,
}

#[derive(clap::Args)]
struct TimestampPredicateProveArgs {
    /// Predicate params from `timestamp predicate-setup`.
    #[arg(long)]
    params: PathBuf,
    /// Predicate witness JSON.
    #[arg(long)]
    witness: PathBuf,
    /// Output predicate proof.
    #[arg(long, default_value = "timestamp-predicate-proof.json")]
    out: PathBuf,
}

#[derive(clap::Args)]
struct TimestampPredicateVerifyArgs {
    /// Predicate params from `timestamp predicate-setup`.
    #[arg(long)]
    params: PathBuf,
    /// Predicate proof file.
    #[arg(long)]
    proof: PathBuf,
    /// Optional receipt JSON to cross-check commitment and block height.
    #[arg(long)]
    receipt: Option<PathBuf>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct TimestampReceipt {
    #[serde(default = "default_commitment_scheme")]
    commitment_scheme: String,
    commitment: String,
    block_height: u64,
    nonce: String,
    doc_hash_lo: String,
    doc_hash_hi: String,
    #[serde(default)]
    doc_hash_sha256: String,
}

#[derive(Debug, Serialize)]
struct TimestampAnchorMeta {
    txid: String,
    network: String,
    commitment: String,
    block_height: Option<u64>,
}

fn default_commitment_scheme() -> String {
    "zectime-poseidon-pallas-v2".to_string()
}

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::EnvFilter::from_default_env())
        .init();

    match Cli::parse().command {
        Command::Setup(args) => run_setup(args),
        Command::Timestamp(args) => match args.command {
            TimestampCommand::Stamp(args) => run_timestamp_stamp(args),
            TimestampCommand::Reveal(args) => run_timestamp_reveal(args),
            TimestampCommand::Verify(args) => run_timestamp_verify(args),
            TimestampCommand::Anchor(args) => run_timestamp_anchor(args).await,
            TimestampCommand::Fetch(args) => run_timestamp_fetch(args).await,
            TimestampCommand::PredicateSetup(args) => run_predicate_setup(args),
            TimestampCommand::PredicateProve(args) => run_predicate_prove(args),
            TimestampCommand::PredicateVerify(args) => run_predicate_verify(args),
        },
    }
}

fn run_setup(args: SetupArgs) -> Result<()> {
    let artifacts = TimestampProvingArtifacts::generate(args.k)?;
    let file = create_file(&args.params)?;
    write_params(&artifacts.params, BufWriter::new(file))?;
    println!("wrote IPA params to {}", args.params.display());
    Ok(())
}

fn run_timestamp_stamp(args: TimestampStampArgs) -> Result<()> {
    let (doc_hash_lo, doc_hash_hi, digest) = hash_file_for_timestamp(&args.file)?;
    let mut nonce_bytes = [0u8; 16];
    OsRng.fill_bytes(&mut nonce_bytes);
    let nonce = u128::from_le_bytes(nonce_bytes);
    let commitment_bytes = compute_commitment_bytes(doc_hash_lo, doc_hash_hi, nonce);
    let receipt = TimestampReceipt {
        commitment_scheme: default_commitment_scheme(),
        commitment: hex_le(&commitment_bytes),
        block_height: args.block_height.unwrap_or(0),
        nonce: format!("{nonce:032x}"),
        doc_hash_lo: format!("{doc_hash_lo:032x}"),
        doc_hash_hi: format!("{doc_hash_hi:032x}"),
        doc_hash_sha256: hex::encode(digest),
    };

    let file = create_file(&args.out)?;
    serde_json::to_writer_pretty(BufWriter::new(file), &receipt)?;
    println!("commitment:   0x{}", receipt.commitment);
    println!("block_height: {}", receipt.block_height);
    println!("wrote receipt to {}", args.out.display());
    Ok(())
}

fn run_timestamp_reveal(args: TimestampRevealArgs) -> Result<()> {
    let receipt = load_receipt(&args.receipt)?;
    let witness = TimestampWitness {
        doc_hash_lo: parse_u128_hex(&receipt.doc_hash_lo, "doc_hash_lo")?,
        doc_hash_hi: parse_u128_hex(&receipt.doc_hash_hi, "doc_hash_hi")?,
        nonce: parse_u128_hex(&receipt.nonce, "nonce")?,
        block_height: receipt.block_height,
    };
    let params = read_params(BufReader::new(File::open(&args.params)?))?;
    let artifacts = TimestampProvingArtifacts::from_params(params)?;
    let proof = prove_timestamp(&artifacts, &witness)?;
    let file = create_file(&args.out)?;
    serde_json::to_writer(BufWriter::new(file), &proof)?;
    print_timestamp_public_inputs(&proof);
    println!("wrote proof to {}", args.out.display());
    Ok(())
}

fn run_timestamp_verify(args: TimestampVerifyArgs) -> Result<()> {
    let params = read_params(BufReader::new(File::open(&args.params)?))?;
    let proof: TimestampProof = decode_proof_file(&args.proof)?;
    let vk = timestamp_verifying_key_for(&params)?;
    verify_timestamp(&params, &vk, &proof.public_inputs, &proof.proof)?;
    if let Some(path) = &args.receipt {
        assert_receipt_matches_open_proof(path, &proof)?;
    }
    print_timestamp_public_inputs(&proof);
    println!("OK: timestamp proof verified");
    Ok(())
}

async fn run_timestamp_anchor(args: TimestampAnchorArgs) -> Result<()> {
    let receipt = load_receipt(&args.receipt)?;
    let commitment = parse_hex_le_commitment(&receipt.commitment)?;
    let rpc = build_rpc(
        args.network,
        args.rpc_url,
        args.from_address,
        args.rpc_user,
        args.rpc_password,
    )?;
    let txid = publish_timestamp(&rpc, commitment).await?;
    let meta = TimestampAnchorMeta {
        txid: hex::encode(txid),
        network: args.network.as_str().to_string(),
        commitment: receipt.commitment,
        block_height: None,
    };
    let file = create_file(&args.out)?;
    serde_json::to_writer_pretty(BufWriter::new(file), &meta)?;
    println!("anchored txid: {}", meta.txid);
    Ok(())
}

async fn run_timestamp_fetch(args: TimestampFetchArgs) -> Result<()> {
    let txid = parse_txid(&args.txid)?;
    let rpc = build_rpc(
        args.network,
        args.rpc_url,
        String::new(),
        args.rpc_user,
        args.rpc_password,
    )?;
    let anchored = fetch_timestamp(&rpc, &txid).await?;
    let commitment = hex_le(&anchored.commitment);
    if let Some(receipt_path) = &args.receipt {
        let receipt = load_receipt(receipt_path)?;
        if receipt.commitment != commitment || receipt.block_height != anchored.block_height {
            anyhow::bail!("receipt does not match fetched anchor");
        }
    }
    println!("txid:         {}", hex::encode(anchored.txid));
    println!("block_height: {}", anchored.block_height);
    println!("commitment:   0x{commitment}");
    if let Some(out) = &args.out {
        let meta = TimestampAnchorMeta {
            txid: hex::encode(anchored.txid),
            network: args.network.as_str().to_string(),
            commitment,
            block_height: Some(anchored.block_height),
        };
        let file = create_file(out)?;
        serde_json::to_writer_pretty(BufWriter::new(file), &meta)?;
    }
    Ok(())
}

fn run_predicate_setup(args: TimestampPredicateSetupArgs) -> Result<()> {
    let artifacts = TimestampPredicateProvingArtifacts::generate(args.k)?;
    let file = create_file(&args.params)?;
    write_params(&artifacts.params, BufWriter::new(file))?;
    println!("wrote predicate params to {}", args.params.display());
    Ok(())
}

fn run_predicate_prove(args: TimestampPredicateProveArgs) -> Result<()> {
    let witness: PredicateWitness =
        serde_json::from_reader(BufReader::new(File::open(&args.witness)?))?;
    let params = read_params(BufReader::new(File::open(&args.params)?))?;
    let artifacts = TimestampPredicateProvingArtifacts::from_params(params)?;
    let proof = prove_timestamp_predicate(&artifacts, &witness)?;
    let file = create_file(&args.out)?;
    serde_json::to_writer(BufWriter::new(file), &proof)?;
    print_predicate_public_inputs(&proof);
    println!("wrote predicate proof to {}", args.out.display());
    Ok(())
}

fn run_predicate_verify(args: TimestampPredicateVerifyArgs) -> Result<()> {
    let params = read_params(BufReader::new(File::open(&args.params)?))?;
    let proof: TimestampPredicateProof = decode_proof_file(&args.proof)?;
    if proof.public_inputs.len() != TIMESTAMP_PREDICATE_PUBLIC_INPUTS {
        anyhow::bail!("wrong predicate public input arity");
    }
    let vk = timestamp_predicate_verifying_key_for(&params)?;
    verify_timestamp_predicate(&params, &vk, &proof.public_inputs, &proof.proof)?;
    if let Some(path) = &args.receipt {
        let receipt = load_receipt(path)?;
        assert_predicate_receipt_matches(&receipt, &proof)?;
    }
    print_predicate_public_inputs(&proof);
    println!("OK: predicate proof verified");
    Ok(())
}

fn hash_file_for_timestamp(path: &PathBuf) -> Result<(u128, u128, [u8; 32])> {
    let mut file =
        File::open(path).with_context(|| format!("failed to open {}", path.display()))?;
    let mut hasher = Sha256::new();
    std::io::copy(&mut file, &mut hasher)?;
    let digest = hasher.finalize();
    let mut full = [0u8; 32];
    full.copy_from_slice(&digest[..32]);
    let lo = u128::from_le_bytes(full[..16].try_into().expect("16 bytes"));
    let hi = u128::from_le_bytes(full[16..32].try_into().expect("16 bytes"));
    Ok((lo, hi, full))
}

fn load_receipt(path: &PathBuf) -> Result<TimestampReceipt> {
    Ok(serde_json::from_reader(BufReader::new(File::open(path)?))?)
}

fn decode_proof_file<T>(path: &PathBuf) -> Result<T>
where
    T: serde::de::DeserializeOwned,
{
    let metadata =
        std::fs::metadata(path).with_context(|| format!("failed to stat {}", path.display()))?;
    if metadata.len() > MAX_PROOF_BYTES {
        anyhow::bail!(
            "proof file {} is too large: {} bytes > {}",
            path.display(),
            metadata.len(),
            MAX_PROOF_BYTES
        );
    }
    let mut reader = BufReader::new(File::open(path)?);
    let decoded = serde_json::from_reader(&mut reader)?;
    Ok(decoded)
}

fn assert_receipt_matches_open_proof(path: &PathBuf, proof: &TimestampProof) -> Result<()> {
    let receipt = load_receipt(path)?;
    let commitment = hex_le(&proof.public_inputs[0]);
    if commitment != receipt.commitment {
        anyhow::bail!("receipt commitment does not match proof commitment");
    }
    let block_height = field_repr_to_u64(&proof.public_inputs[1])?;
    if block_height != receipt.block_height {
        anyhow::bail!("receipt block_height does not match proof block_height");
    }
    Ok(())
}

fn assert_predicate_receipt_matches(
    receipt: &TimestampReceipt,
    proof: &TimestampPredicateProof,
) -> Result<()> {
    let commitment = hex_le(&proof.public_inputs[0]);
    if receipt.commitment != commitment {
        anyhow::bail!("receipt commitment does not match predicate proof");
    }
    let block_height = field_repr_to_u64(&proof.public_inputs[1])?;
    if receipt.block_height != block_height {
        anyhow::bail!("receipt block_height does not match predicate proof block_height");
    }
    Ok(())
}

fn build_rpc(
    network: Network,
    url: Url,
    from_address: String,
    rpc_user: Option<String>,
    rpc_password: Option<String>,
) -> Result<ZalletRpc> {
    let mut config = ZalletConfig::for_network(network, url, from_address);
    if let (Some(user), Some(password)) = (rpc_user, rpc_password) {
        config = config.with_auth(ZalletAuth { user, password });
    }
    if let Ok(path) = std::env::var("ZECTIME_WALLET_DB_PATH") {
        if !path.is_empty() {
            config = config.with_wallet_db_path(path);
        }
    }
    ZalletRpc::new(config).context("failed to construct zallet RPC client")
}

fn parse_network(s: &str) -> Result<Network, String> {
    s.parse::<Network>().map_err(|e| e.to_string())
}

fn parse_txid(s: &str) -> Result<TxId> {
    let bytes = hex::decode(s).with_context(|| format!("invalid txid hex `{s}`"))?;
    let len = bytes.len();
    bytes
        .try_into()
        .map_err(|_| anyhow!("txid decoded to {len} bytes; expected 32"))
}

fn parse_hex_le_commitment(hex_str: &str) -> Result<[u8; 32]> {
    let trimmed = hex_str.strip_prefix("0x").unwrap_or(hex_str);
    let decoded = hex::decode(trimmed)?;
    if decoded.len() != 32 {
        anyhow::bail!("commitment must decode to 32 bytes");
    }
    let mut le = [0u8; 32];
    for (i, b) in decoded.iter().enumerate() {
        le[31 - i] = *b;
    }
    Ok(le)
}

fn parse_u128_hex(value: &str, field: &str) -> Result<u128> {
    let trimmed = value.strip_prefix("0x").unwrap_or(value);
    u128::from_str_radix(trimmed, 16)
        .with_context(|| format!("field `{field}` is not valid hex u128"))
}

fn field_repr_to_u64(bytes: &[u8; 32]) -> Result<u64> {
    for (i, b) in bytes.iter().enumerate().skip(8) {
        if *b != 0 {
            return Err(anyhow!("value does not fit in u64; non-zero byte at {i}"));
        }
    }
    Ok(u64::from_le_bytes(bytes[..8].try_into().expect("8 bytes")))
}

fn print_timestamp_public_inputs(proof: &TimestampProof) {
    for (i, bytes) in proof.public_inputs.iter().enumerate() {
        let label = match i {
            0 => "commitment",
            1 => "block_height",
            _ => "unknown",
        };
        println!("  [{i}] {label} = 0x{}", hex_le(bytes));
    }
}

fn print_predicate_public_inputs(proof: &TimestampPredicateProof) {
    for (i, bytes) in proof.public_inputs.iter().enumerate() {
        let label = match i {
            0 => "commitment",
            1 => "block_height",
            2 => "claim_hash",
            _ => "unknown",
        };
        println!("  [{i}] {label} = 0x{}", hex_le(bytes));
    }
}

fn hex_le(bytes: &[u8; 32]) -> String {
    let mut s = String::with_capacity(64);
    for b in bytes.iter().rev() {
        let _ = write!(&mut s, "{b:02x}");
    }
    s
}

fn create_file(path: &PathBuf) -> Result<File> {
    OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .open(path)
        .with_context(|| format!("failed to create {}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn proof_with_height(commitment: [u8; 32], block_height: u64) -> TimestampPredicateProof {
        let mut height = [0u8; 32];
        height[..8].copy_from_slice(&block_height.to_le_bytes());
        TimestampPredicateProof {
            public_inputs: vec![commitment, height, [0x66; 32]],
            proof: Vec::new(),
        }
    }

    fn receipt_for(commitment: [u8; 32], block_height: u64) -> TimestampReceipt {
        TimestampReceipt {
            commitment_scheme: default_commitment_scheme(),
            commitment: hex_le(&commitment),
            block_height,
            nonce: "22".repeat(16),
            doc_hash_lo: "33".repeat(16),
            doc_hash_hi: "44".repeat(16),
            doc_hash_sha256: "55".repeat(32),
        }
    }

    #[test]
    fn predicate_receipt_match_requires_block_height() {
        let commitment = [0x11; 32];
        let receipt = receipt_for(commitment, 100);
        let proof = proof_with_height(commitment, 100);

        assert!(assert_predicate_receipt_matches(&receipt, &proof).is_ok());

        let wrong_height = proof_with_height(commitment, 101);
        let err = assert_predicate_receipt_matches(&receipt, &wrong_height).unwrap_err();
        assert!(
            err.to_string().contains("block_height"),
            "unexpected error: {err}"
        );
    }
}
